export const menuContent = {
  Core: [
    // 'Clock',
    // 'Context',
    // 'Delay',
    'Destination',
    // 'Draw',
    // 'Emitter',
    'Gain',
    // 'Quantizer',
    // 'Sequencer'
    // 'Listener',
    // 'OfflineContext',
    // 'Param',
    // 'Tone',
    // 'ToneAudioBuffer',
    // 'ToneAudioBuffers',
    'Transport',    
  ], 

  Source: [
    'AMOscillator',
    'FMOscillator',
    'FatOscillator',
    // 'GrainPlayer',
    'LFO',
    'Noise',
    'OmniOscillator',
    'Oscillator',
    'PWMOscillator',
    // 'Player',
    // 'Players',
    'PulseOscillator',
    // 'ToneBufferSource',
    // 'ToneOscillatorNode',
    // 'UserMedia',
  ], 

  Instrument: [
    // 'AMSynth',
    // 'DuoSynth',
    // 'FMSynth',
    'MembraneSynth',
    'MetalSynth',
    // 'MonoSynth',
    'NoiseSynth',
    'PluckSynth',
    // 'PolySynth',
    // 'Sampler',
    'Synth',
  ],

  Effect: [
    'AutoFilter',
    'AutoPanner',
    'AutoWah',
    'BitCrusher',
    'Chebyshev',
    'Chorus',
    'Distortion',
    'FeedbackDelay',
    'Freeverb',
    'FrequencyShifter',
    'Phaser',
    'PingPongDelay',
    'PitchShift',
    'Reverb',
    
    'Tremolo',
    'Vibrato',

  ], 

  Component:[
    'AmplitudeEnvelope',
    // 'Analyser',
    // 'BiquadFilter',
    'Channel',
    'Compressor',
    // 'Convolver',
    'CrossFade',
    // 'DCMeter',
    'EQ3',
    'Envelope',
    // 'FFT',
    'FeedbackCombFilter',
    'Filter',
    'Follower',
    'FrequencyEnvelope',
    // 'Gate',
    'Limiter',
    'LowpassCombFilter',
    'Merge',
    // 'Meter',
    // 'MidSideCompressor',
    // 'MidSideMerge',
    // 'MidSideSplit',
    // 'Mono',
    // 'MultibandCompressor',
    // 'MultibandSplit',
    // 'OnePoleFilter',
    // 'PanVol',
    // 'Panner',
    // 'Panner3D',
    // 'PhaseShiftAllpass',
    // 'Recorder',
    // 'Solo',
    // 'Split',
    // 'Volume',
    // 'Waveform',
  ],
  Signal: [
    "Abs",
    "Add",
    'AudioToGain',
    'GainToAudio',
    'GreaterThan',
    'GreaterThanZero',
    'Multiply',
    'Negate',
    'Pow',
    'Scale',
    'ScaleExp',
    'Signal',
    'Subtract',
    // 'ToneConstantSource',
    // 'WaveShaper',
    // 'Zero',
  ]
}